import type { TripContent } from "./types"

export const northVietnam: TripContent = {
  coverWeb: "/north-vietnam/northvietnam-cover-web.png",
  coverMobile: "/north-vietnam/northvietnam-cover-mobile.png",
  heroSubtitle: "Rice terraces, mountain villages, limestone bays and immersive local experiences",

  stopsCities: "Hanoi · Sapa · Tam Coc · Ha Long",
  groupSize: "Max 12",

  stops: [
    {
      id: 1,
      city: "Hanoi",
      daysLabel: "Days 1–3",
      subtitle: "Vietnam's Capital",
      mapSvg: "/maps/north-vietnam-step-1.svg",
      objectPosition: "center center",
      highlights: [
        "Airport transfer & boutique hotel check-in",
        "Ngoc Son Temple on Hoan Kiem Lake",
        "Iconic egg coffee experience",
        "Guided street food tour from 16:00",
        "Optional: Hanoi's vibrant gay bars",
        "Full city discovery on Day 2",
      ],
      gallery: [
        { src: "/north-vietnam/gallery/hanoi/hanoi-01.png", caption: "Visit Ngoc Son Temple, on a small island in Hoan Kiem Lake" },
        { src: "/north-vietnam/gallery/hanoi/hanoi-02.png", caption: "Guided street food tour in Hanoi Old Quarter" },
        { src: "/north-vietnam/gallery/hanoi/hanoi-03.png", caption: "Hanoi's iconic egg coffee, creamy, sweet and unique" },
        { src: "/north-vietnam/gallery/hanoi/hanoi-04.png", caption: "Drinks at one of Hanoi's vibrant gay bars" },
      ],
    },
    {
      id: 2,
      city: "Sapa",
      daysLabel: "Days 4–6",
      subtitle: "Mountain Escape",
      mapSvg: "/maps/north-vietnam-step-2.svg",
      objectPosition: "center 40%",
      highlights: [
        "5–6h scenic minivan from Hanoi",
        "Guided trek through rice terraces & villages",
        "Overnight in 5-star mountain hotel",
        "Cable Car to Fansipan: Vietnam's highest peak",
        "Traditional Sapa Hot Pot dinner",
      ],
      gallery: [
        { src: "/north-vietnam/gallery/sapa/sapa-01.png", caption: "Trek through bamboo forests, rice terraces, villages and valleys" },
        { src: "/north-vietnam/gallery/sapa/sapa-02.png", caption: "Meet local communities and observe traditional crafts" },
        { src: "/north-vietnam/gallery/sapa/sapa-03.png", caption: "Cable Car Fansipan experience to Vietnam's highest mountain" },
        { src: "/north-vietnam/gallery/sapa/sapa-04.png", caption: "Traditional Sapa Hot Pot" },
      ],
    },
    {
      id: 3,
      city: "Tam Coc",
      daysLabel: "Days 7–9",
      subtitle: "Ha Long Bay on Land",
      mapSvg: "/maps/north-vietnam-step-3.svg",
      objectPosition: "center 60%",
      highlights: [
        "Scenic minivan direct from Sapa",
        "Dragon Mountain sunrise viewpoint",
        "Scenic boat trip through caves & cliffs",
        "Cycling tour: Thung Nang Lake & Bich Dong Pagoda",
        "Boutique eco-resort with pool",
      ],
      gallery: [
        { src: "/north-vietnam/gallery/tamcoc/tamcoc-01.png", caption: "Early morning climb to Dragon Mountain" },
        { src: "/north-vietnam/gallery/tamcoc/tamcoc-02.png", caption: "Boat trip through rivers, cliffs and caves" },
        { src: "/north-vietnam/gallery/tamcoc/tamcoc-03.png", caption: "Hidden cycling tour through the countryside of Tam Coc" },
        { src: "/north-vietnam/gallery/tamcoc/tamcoc-04.png", caption: "Bich Dong Pagoda" },
      ],
    },
    {
      id: 4,
      city: "Ha Long Bay",
      daysLabel: "Days 10–11",
      subtitle: "Luxury Yacht Cruise",
      mapSvg: "/maps/north-vietnam-step-4.svg",
      objectPosition: "center 70%",
      highlights: [
        "3h drive + private boat transfer to yacht",
        "Kayaking through limestone islands",
        "Cat Ba Island & Three Peaches Beach",
        "Full board dining + sunset cocktails on deck",
        "Private balcony cabin on luxury yacht",
      ],
      gallery: [
        { src: "/north-vietnam/gallery/halong/halongbay-01.png", caption: "3-Day, 2-night full-board luxury yacht experience" },
        { src: "/north-vietnam/gallery/halong/halongbay-02.png", caption: "Cat Ba Island beach" },
        { src: "/north-vietnam/gallery/halong/halongbay-03.png", caption: "Spring roll making cooking class on the yacht" },
        { src: "/north-vietnam/gallery/halong/halongbay-04.png", caption: "Visit a majestic cave filled with shimmering stalactites" },
      ],
    },
    {
      id: 5,
      city: "Return to Hanoi",
      galleryCity: "Hanoi",
      daysLabel: "Day 12",
      subtitle: "Farewell",
      mapSvg: "/maps/north-vietnam-step-5.svg",
      objectPosition: "center center",
      highlights: [
        "Final morning free in Hanoi",
        "Train Street visit",
        "Farewell lunch with the group",
        "Private airport transfer",
      ],
      gallery: [
        { src: "/north-vietnam/gallery/hanoi/hanoi-21.png", caption: "Iconic Train Street visit" },
        { src: "/north-vietnam/gallery/hanoi/hanoi-22.png", caption: "Final stroll and last shopping" },
        { src: "/north-vietnam/gallery/hanoi/hanoi-23.png", caption: "Curated farewell dinner" },
        { src: "/north-vietnam/gallery/hanoi/hanoi-24.png", caption: "Last gay night out in Vietnam's vibrant capital" },
      ],
    },
  ],

  comfortCards: [
    {
      image: "/north-vietnam/accommodation/A.Hanoi.jpg",
      location: "Hanoi",
      title: "Premium 4-Star Hotel",
      tag: "3 nights · Breakfast included",
      description: "Elegantly located hotel in central Hanoi, with breakfast included.",
    },
    {
      image: "/north-vietnam/accommodation/A.Sapa.jpg",
      location: "Sapa",
      title: "5-Star Mountain Resort",
      tag: "3 nights · Breakfast included",
      description: "Cloud-wrapped luxury in Sapa, a perfect retreat after a day of trekking in the terraces.",
    },
    {
      image: "/north-vietnam/accommodation/A.TamCoc.jpg",
      location: "Tam Coc",
      title: "Premium 4-Star Hotel",
      tag: "3 nights · Breakfast included",
      description: "Boutique eco-resort with a pool, nestled in Ninh Binh's stunning karst landscape.",
    },
    {
      image: "/accommodation/halong-1.jpg",
      location: "Ha Long Bay",
      title: "Luxury Yacht Cruise",
      tag: "2 nights · Full board",
      description: "Private balcony cabins on a 5-star yacht. Full board, sunset cocktails on deck.",
    },
    {
      image: "/north-vietnam/accommodation/A.Minivan.jpg",
      location: "Northern Vietnam",
      title: "Premium Minivan",
      tag: "Private transfers",
      description: "Enjoy relaxed journeys across Northern Vietnam in premium minivans",
    },
  ],

  included: [
    "Group guidance and assistance during the stay",
    "9 nights with breakfast in premium 4 and 5-star hotels",
    "2 nights on a 5-star exclusive yacht with full board",
    "6 selected additional meals",
    "All included activities listed in the itinerary",
    "Premium air-conditioned minivans throughout the trip",
    "Private airport transfer on arrival and departure",
    "Organisation fees, taxes and local charges",
    "Welcome gift package",
  ],

  notIncluded: [
    "International flights",
    "Additional meals not listed in the programme",
    "Travel insurance",
    "Personal expenses",
    "Extra activities not included in the programme",
    "Additional private assistance outside the programme",
    "Early check-in on arrival day",
    "Late check-out on departure day",
  ],

  brochureUrl: "https://drive.google.com/file/d/1FBiN1QZ_wmKvMMt8d0Q-dF3Rtm8Yqjm1/view",
}
